version: '3.8'

services:
  php-apache-g7:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-apache-g7
    restart: always
    volumes:
      - ./src:/var/www/html
      # - ./vendor:/var/www/html/vendor
    networks:
      - traefik_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.apig7.rule=Host(`api.g7.maximizebot.com.br`)"
      - "traefik.http.routers.apig7.entrypoints=websecure"
      - "traefik.http.routers.apig7.tls.certresolver=myresolver"
      - "traefik.http.services.apig7.loadbalancer.server.port=80"
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      SMTP_HOST: "${SMTP_HOST}"
      SMTP_USER: "${SMTP_USER}"
      SMTP_PASSWORD: "${SMTP_PASSWORD}"
      SECRET: "${SECRET}"
    env_file:
      - .env

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - traefik_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
    ports:
      - "8089:80"
    networks:
      - traefik_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.g7.maximizebot.com.br`)"
      - "traefik.http.routers.pgadmin.entrypoints=websecure"
      - "traefik.http.routers.pgadmin.tls.certresolver=myresolver"
      - "traefik.http.services.pgadmin.loadbalancer.server.port=80"

networks:
  traefik_net:
    external: true

volumes:
  postgres_data:
